# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1745JM0dmTANxCtPFNKZtIKBbi6i_nGvb
"""



# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_datareader as data
plt.style.use('fivethirtyeight')
# %matplotlib inline

import yfinance as yf
import datetime as dt

stock = "POWERGRID.NS","AAPL","NVDA", "MSFT", "GOOG", "AMZN",  "2222.SR", "META", "META", "TSM", "LLY", "AVGO", "TSLA", "NVO", "WMT", "UNH", "XOM", "V", "JPM", "JNJ", "MA",

start = dt.datetime(2000,1,1)
end = dt.datetime.now()
df = yf.download(stock, start, end)

df.head()

df.shape

df.info()

df.isnull().sum()

df.describe()

df = df.reset_index()

df.shape

df.head()

df.columns

data01 = df.to_csv('stock.csv')

data01 = pd.read_csv('stock.csv')
data01.head()



# candlesticks
import plotly.graph_objects as go

# When saving to csv, set index=False to include the index as a column named 'Date'
# data01 = df.to_csv('stock.csv', index=False)  # Previous incorrect line
# OR, load the data making sure to use the first column as index
data01 = pd.read_csv('stock.csv', index_col=0) # Suggested fix

fig = go.Figure(data=[go.Candlestick(x=data01.index,
                open=data01['Open'],
                high=data01['High'],
                low=data01['Low'],
                close=data01['Close'])])

fig.show()

df.head()

plt.figure(figsize=(50,40))
plt.plot(df['Close'], label='Closing price', linewidth=1)
plt.title(f'{stock} closing prices over time')
plt.legend()
plt.show()

plt.figure(figsize=(50,40))
plt.plot(df['High'], label='High price', linewidth=1)
plt.title(f'{stock} High prices over time')
plt.legend()
plt.show()

plt.figure(figsize=(30,6))
plt.plot(df['Volume'], label='Volume price', linewidth=1)  # Changed 'volume' to 'Volume'
plt.title(f'{stock} Volume prices over time')
plt.legend()
plt.show()

"""# New Section

# New Section
"""

temp_data = [10,20,30,40,50,60,70,80,90,]
print(sum(temp_data[2:7])/5)

import pandas as pd
df01 = pd.DataFrame(temp_data)

df01.rolling(5).mean()

ma100 = df01[0].rolling(100).mean() # Access the first column using its index (0)

ma100

ma200 = df['Close'].rolling(200).mean()  # Access the 'Close' column using brackets

plt.figure(figsize=(12, 6))
plt.plot(df.Close, label = f'{stock} Close Price', linewidth = 1)
# Calculate and plot the Exponential Moving Average (EMA) instead of using the undefined 'ema100' and 'ema200'
ema100 = df['Close'].ewm(span=100, adjust=False).mean()  # Calculate EMA with span 100
ema200 = df['Close'].ewm(span=200, adjust=False).mean()  # Calculate EMA with span 200
plt.plot(ema100, label = f'{stock} Exp. Moving Average 100 Price', linewidth = 1)
plt.plot(ema200, label = f'{stock} Exp. Moving Average 200 Price', linewidth = 1)
plt.legend()
plt.show()

data_training = pd.DataFrame(df['Close'][0:int(len(df)*0.70)])
data_testing = pd.DataFrame(df['Close'][int(len(df)*0.70): int(len(df))])

data_training.shape

data_testing.shape

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range = (0, 1))

data_training_array = scaler.fit_transform(data_training)

data_training_array

data_training_array.shape[0]

x_train = []
y_train = []

for i in range(100, data_training_array.shape[0]):
    x_train.append(data_training_array[i-100:i])
    y_train.append(data_training_array[i, 0])

x_train, y_train  = np.array(x_train), np.array(y_train)

x_train.shape

from keras.layers import Dense, Dropout, LSTM
from keras.models import Sequential

model = Sequential()

model.add(LSTM(units = 50, activation = 'relu', return_sequences = True, input_shape = (x_train.shape[1],1)))
model.add(Dropout(0.2))

model.add(LSTM(units = 60, activation = 'relu', return_sequences = True))
model.add(Dropout(0.3))

model.add(LSTM(units = 80, activation = 'relu', return_sequences = True))
model.add(Dropout(0.4))

model.add(LSTM(units = 120, activation = 'relu'))
model.add(Dropout(0.5))

model.add(Dense(units = 1))

model.summary()

model = Sequential()

# Reshape x_train to have the correct number of features
num_features = x_train.shape[2]  # Get the actual number of features from x_train
# Assuming x_train.shape is (num_samples, num_timesteps, num_features)

# Update the input shape for the first LSTM layer
model.add(LSTM(units=50, activation='relu', return_sequences=True,
               input_shape=(x_train.shape[1], num_features)))  # Use num

past_100_days = data_training.tail(100)

final_df = pd.concat([past_100_days, data_testing], ignore_index=True)

final_df.head()

input_data = scaler.fit_transform(final_df)

x_test = []
y_test = []

for i in range(100, input_data.shape[0]):
    x_test.append(input_data[i-100:i])
    y_test.append(input_data[i, 0])

x_test, y_test  = np.array(x_test), np.array(y_test)

x_test.shape

# ... (previous code)

# Predict values using the model:
y_predicted = model.predict(x_test)

# Now, access the shape:
y_predicted.shape

scaler.scale_

scaler_factor = 1 / 0.0035166
y_predicted = y_predicted * scaler_factor
y_test = y_test * scaler_factor

plt.figure(figsize=(12, 6))
plt.plot(y_test, label = 'Original Price', linewidth = 1)
# Assuming y_predicted is 3D, we take the first element from the last two dimensions:
plt.plot(y_predicted[:, 0, 0], label = 'Predicted Price', linewidth = 1)
plt.legend()
plt.show()

model.save('stock_dl_model.h5')

!pip install gradio yfinance matplotlib pandas requests --quiet

import gradio as gr
import yfinance as yf
import matplotlib.pyplot as plt
import pandas as pd
import requests
from io import BytesIO
from PIL import Image

# ✅ 25 Company List with Logos
company_data = {
    "Apple": {"ticker": "AAPL", "logo": "https://logo.clearbit.com/apple.com"},
    "Amazon": {"ticker": "AMZN", "logo": "https://logo.clearbit.com/amazon.com"},
    "Google": {"ticker": "GOOGL", "logo": "https://logo.clearbit.com/google.com"},
    "Microsoft": {"ticker": "MSFT", "logo": "https://logo.clearbit.com/microsoft.com"},
    "Meta (Facebook)": {"ticker": "META", "logo": "https://logo.clearbit.com/facebook.com"},
    "Tesla": {"ticker": "TSLA", "logo": "https://logo.clearbit.com/tesla.com"},
    "NVIDIA": {"ticker": "NVDA", "logo": "https://logo.clearbit.com/nvidia.com"},
    "Netflix": {"ticker": "NFLX", "logo": "https://logo.clearbit.com/netflix.com"},
    "Intel": {"ticker": "INTC", "logo": "https://logo.clearbit.com/intel.com"},
    "AMD": {"ticker": "AMD", "logo": "https://logo.clearbit.com/amd.com"},
    "IBM": {"ticker": "IBM", "logo": "https://logo.clearbit.com/ibm.com"},
    "Adobe": {"ticker": "ADBE", "logo": "https://logo.clearbit.com/adobe.com"},
    "Oracle": {"ticker": "ORCL", "logo": "https://logo.clearbit.com/oracle.com"},
    "PayPal": {"ticker": "PYPL", "logo": "https://logo.clearbit.com/paypal.com"},
    "Salesforce": {"ticker": "CRM", "logo": "https://logo.clearbit.com/salesforce.com"},
    "Cisco": {"ticker": "CSCO", "logo": "https://logo.clearbit.com/cisco.com"},
    "Shopify": {"ticker": "SHOP", "logo": "https://logo.clearbit.com/shopify.com"},
    "Zoom": {"ticker": "ZM", "logo": "https://logo.clearbit.com/zoom.us"},
    "Qualcomm": {"ticker": "QCOM", "logo": "https://logo.clearbit.com/qualcomm.com"},
    "Uber": {"ticker": "UBER", "logo": "https://logo.clearbit.com/uber.com"},
    "Boeing": {"ticker": "BA", "logo": "https://logo.clearbit.com/boeing.com"},
    "Ford": {"ticker": "F", "logo": "https://logo.clearbit.com/ford.com"},
    "General Electric": {"ticker": "GE", "logo": "https://logo.clearbit.com/ge.com"},
    "Coca-Cola": {"ticker": "KO", "logo": "https://logo.clearbit.com/coca-colacompany.com"},
    "PepsiCo": {"ticker": "PEP", "logo": "https://logo.clearbit.com/pepsico.com"},
}

# 🔮 Dummy ML prediction (replace with your actual model)
def predict_stock(company_name, days):
    ticker = company_data[company_name]["ticker"]
    logo_url = company_data[company_name]["logo"]

    # 📊 Download data
    df = yf.download(ticker, start="2000-01-01")
    df["Prediction"] = df["Close"].rolling(window=5).mean()  # Replace with real model

    # 🖼️ Plot
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(df.index, df["Close"], label="Actual", linewidth=2)
    ax.plot(df.index, df["Prediction"], label="Prediction", linestyle="--")
    ax.set_title(f"{company_name} Stock Price & ML Forecast")
    ax.set_xlabel("Date")
    ax.set_ylabel("Price (USD)")
    ax.grid(True)
    ax.legend()

    # 🖼️ Load logo image
    try:
        response = requests.get(logo_url)
        logo = Image.open(BytesIO(response.content))
    except:
        logo = None

    return fig, logo

# 🎨 Gradio Interface
with gr.Blocks() as demo:
    gr.Markdown("## 💹 AI-Powered Stock Forecasting App")
    gr.Markdown("Select a company to view historical trends and ML predictions. Powered by Python 🤖")

    with gr.Row():
        dropdown = gr.Dropdown(choices=list(company_data.keys()), label="Choose a Company")
        slider = gr.Slider(1, 30, step=1, value=7, label="Prediction Days")

    with gr.Row():
        plot_output = gr.Plot(label="Prediction Chart")
        logo_output = gr.Image(label="Company Logo", type="pil")

    button = gr.Button("Predict Stock Trend")

    button.click(
        fn=predict_stock,
        inputs=[dropdown, slider],
        outputs=[plot_output, logo_output]
    )

# 🚀 Launch in Colab
demo.launch(share=True)

